/nologo
/optimize+
/debug-
/unsafe-
/warn:0
/out:c:/builds/mindpowered/logic/ip-tools/build/vcs/csharp/bin/iptools.dll
/target:library
/reference:c:/builds/mindpowered/logic/ip-tools/build/vcs/csharp/bin/maglev.dll
src\EnumValue.cs
src\Type.cs
src\UInt.cs
src\iptools\IPTools.cs
src\mindpowered\iptools\IPTools.cs